server:
  port: 8080
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE