server:
  port: 9000
spring:
  application:
    name: delivery-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pos_db
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  cloud:
    stream:
      function:
        bindings:
          generateWaybill-in-0:
            waybill
      bindings:
        waybill:
          destination: order
    function:
      definition: generateWaybill


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
